-- Creating seed data for the fans database
INSERT INTO bars (barName) VALUES ("The Local - Pacific Beach");
INSERT INTO bars (barName) VALUES ("PB Alehouse - Pacific Beach");
INSERT INTO bars (barName) VALUES ("San Diego Brewing Company - Mission Valley");
INSERT INTO bars (barName) VALUES ("Bare Back Grill - Pacific Beach");
INSERT INTO bars (barName) VALUES ("McGregor's Grill and Alehouse - Mission Valley");
INSERT INTO bars (barName) VALUES ("Raglan Public House");
INSERT INTO bars (barName) VALUES ("Mother's Saloon");
INSERT INTO bars (barName) VALUES ("Wonderland Ocean Pub - Ocean Beach");
INSERT INTO bars (barName) VALUES ("PB Cantina - Pacific Beach");
INSERT INTO bars (barName) VALUES ("Dave's Tavern - Pacific Beach");
INSERT INTO bars (barName) VALUES ("Catalina Lounge - Ocean Beach");
INSERT INTO bars (barName) VALUES ("The Tipsy Crow - Gaslamp");
INSERT INTO bars (barName) VALUES ("Henry's Pub - Gaslamp");
INSERT INTO bars (barName) VALUES ("Dirty Birds - Pacific Beach");
INSERT INTO bars (barName) VALUES ("The Local Eatery & Drinking Hole - Gaslamp");
INSERT INTO bars (barName) VALUES ("Sycamore Den - Normal Heights");
INSERT INTO bars (barName) VALUES ("Elbow Room - Kearny Mesa");
INSERT INTO bars (barName) VALUES ("Bub's Dive Bar - Pacific Beach");
INSERT INTO bars (barName) VALUES ("Jolt'n Joe's - Gaslamp");
INSERT INTO bars (barName) VALUES ("Kaminski's Sports Lounge and BBQ - Poway");
INSERT INTO bars (barName) VALUES ("The Alley - Carlsbad");
INSERT INTO bars (barName) VALUES ("True North Tavern - North Park");
INSERT INTO bars (barName) VALUES ("East Village Tavern & Bowl - East Village");
INSERT INTO bars (barName) VALUES ("Miss B's Coconut Club - Mission Beach");
INSERT INTO bars (barName) VALUES ("Rookies - Oceanside");
INSERT INTO bars (barName) VALUES ("Rookies - Oceanside");
INSERT INTO bars (barName) VALUES ("Guava Beach - Mission Beach");
INSERT INTO bars (barname) VALUES ("Chief's Burgers & Brew - Solana Beach");
INSERT INTO bars (barName) VALUES ("Backyard Kitchen & Tap - Pacific Beach");
INSERT INTO bars (barName) VALUES ("Truckstop - Pacific Beach");
INSERT INTO bars (barName) VALUES ("Kansas City Barbeque - Downtown");
INSERT INTO bars (barName) VALUES ("Bayside Landing - Pacific Beach");
INSERT INTO bars (barName) VALUES ("High Dive Bar & Grill - Bay Park");
INSERT INTO bars (barName) VALUES ("Bub's at the Ballpark - East Village");
INSERT INTO bars (barName) VALUES ("Barleymash - Gaslamp");
INSERT INTO bars (barName) VALUES ("Oggi's - numerous San Diego locations");
INSERT INTO bars (barName) VALUES ("PB Shore Club - Pacific Beach");
INSERT INTO bars (barName) VALUES ("Rosie O'Grady's - Normal Heights");
INSERT INTO bars (barName) VALUES ("Cheers Bar & Grill - Carmel Valley");
INSERT INTO bars (barName) VALUES ("Buffalo Wild Wings - Chula Vista Center");
INSERT INTO bars (barName) VALUES ("Sunshine Company Saloon - Ocean Beach");
INSERT INTO bars (barName) VALUES ("Johnny V - Pacific Beach");
INSERT INTO bars (barName) VALUES ("The Grand - El Cajon");
INSERT INTO bars (barName) VALUES ("UNION Kitchen & Tap - Gaslamp");
INSERT INTO bars (barName) VALUES ("Knotty Barrel - East Village");
INSERT INTO bars (barName) VALUES ("U31 Bar - North Park");
INSERT INTO bars (barName) VALUES ("Avenue - Pacific Beach");
INSERT INTO bars (barName) VALUES ("Quad Alehouse - Gaslamp");
INSERT INTO bars (barName) VALUES ("Gaslamp Tavern - Gaslamp");
INSERT INTO bars (barName) VALUES ("The Tilted Stick - Ocean Beach");
INSERT INTO bars (barName) VALUES ("Philly Frank's Steaks - San Marcos");
INSERT INTO bars (barName) VALUES ("Winston's Beach Club - Ocean Beach");
INSERT INTO bars (barName) VALUES ("Latitude 32 - Pacific Beach");
INSERT INTO bars (barName) VALUES ("55 Yard Line - San Marcos");
INSERT INTO bars (barName) VALUES ("710 Beach Club - Pacific Beach");
INSERT INTO bars (barName) VALUES ("Rosie O'Grady's - Normal Heights");
INSERT INTO bars (barName) VALUES ("Gerlando's Pizzeria - College East");
INSERT INTO bars (barName) VALUES ("Kaminski's Sports Lounge & BBQ - Poway");
INSERT INTO bars (barName) VALUES ("The Dog - Pacific Beach");
INSERT INTO bars (barName) VALUES ("Knotty Barrel - East Village");
INSERT INTO bars (barName) VALUES ("El Prez/Red's Saloon - Pacific Beach");
INSERT INTO bars (barName) VALUES ("Kaminski's Sports Lounge & BBQ - Poway");
INSERT INTO bars (barName) VALUES ("Guava Beach - Mission Beach");
INSERT INTO bars (barName) VALUES ("Dirty Birds - Pacific Beach");
INSERT INTO bars (barName) VALUES ("Legendary McDini's - National City");
INSERT INTO bars (barName) VALUES ("Dave & Buster's - Mission Valley");
INSERT INTO bars (barName) VALUES ("Rookies - Oceanside");
INSERT INTO bars (barName) VALUES ("Arizona Cafe - Ocean Beach");
INSERT INTO bars (barName) VALUES ("Coaster Saloon - Mission Beach");
INSERT INTO bars (barName) VALUES ("The Silver Fox - Pacific Beach");
INSERT INTO bars (barName) VALUES ("Pizza Port - Solana Beach");
INSERT INTO bars (barName) VALUES ("Cerveza Jack's - Pacific Beach");
INSERT INTO bars (barName) VALUES ("Bootlegger - East Village");
INSERT INTO bars (barName) VALUES ("The Saddle Bar - Solana Beach");
INSERT INTO bars (barName) VALUES ("Thruster's Lounge - Pacific Beach");
INSERT INTO bars (barName) VALUES ("The Brew Project - Hillcrest");
INSERT INTO bars (barName) VALUES ("OB Noodle House Bar 1502 - Ocean Beach");
INSERT INTO bars (barName) VALUES ("Effin's Pub and Grill - Rolando");
INSERT INTO bars (barName) VALUES ("McFadden's Restaurant and Saloon - Gaslamp");