-- Creating seed data for the sport database --
INSERT INTO sport (team_name, league) VALUES ("Buffalo Bills", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Miami Dolphins", "NFL");
INSERT INTO sport (team_name, league) VALUES ("New England Patriots", "NFL");
INSERT INTO sport (team_name, league) VALUES ("New York Jets", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Baltimore Ravens", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Cincinnati Dolphins", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Cleveland Browns", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Pittsburgh Steelers", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Houston Texans", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Indianapolis Colts", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Jacksonville Jaguars", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Tennessee Titans", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Denver Broncos", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Kansas City Chiefs", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Los Angeles Chargers", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Oakland Raiders", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Dallas Cowboys", "NFL");
INSERT INTO sport (team_name, league) VALUES ("New York Giants", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Philadelphia Eagles", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Washington Redskins", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Chicago Bears", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Detroit Lions", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Green Bay Packers", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Minnesota Vikings", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Atlanta Falcons", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Carolina Panthers", "NFL");
INSERT INTO sport (team_name, league) VALUES ("New Orleans Saints", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Tampa Bay Buccaneers", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Arizona Cardinals", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Los Angeles Rams", "NFL");
INSERT INTO sport (team_name, league) VALUES ("San Francisco 49ers", "NFL");
INSERT INTO sport (team_name, league) VALUES ("Seattle Seahawks", "NFL");
